environment_suffix: "_preprod"
project_slug: "{{ base_project_slug }}{{ environment_suffix }}"
project_dir: "{{ project_base_dir }}{{ environment_suffix }}"

website_hostname: "preprod-showcase.iarbre.fr"
website_redirect_hostnames: []
hugo_build_flags: "--buildDrafts --buildFuture --buildExpired"
use_password: true

website_branch: dev
docs_branch: dev
