name: Build Documentation

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, '[no doc]')"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set environment
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=preprod" >> $GITHUB_ENV
          fi

      - name: Build and deploy doc
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: docs.yml
          directory: deploy
          vault_password: ${{ secrets.ANSIBLE_VAULT_KEY }}
          options: |
            -l ${{ env.ENVIRONMENT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
