name: Website checks

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  docs-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - run: pip install -r mkdocs-requirements.txt

      - name: Build MkDocs documentation
        run: mkdocs build --strict

  hugo-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.145.0"

      - name: Build Hugo site
        run: hugo build --minify
        working-directory: ./website
